#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5D2EEE6F6F349D7C (tim@centricular.com)
#
Name     : gst-plugins-bad
Version  : 1.18.5
Release  : 88
URL      : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.18.5.tar.xz
Source0  : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.18.5.tar.xz
Source1  : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.18.5.tar.xz.asc
Summary  : GStreamer WebRTC support
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: gst-plugins-bad-bin = %{version}-%{release}
Requires: gst-plugins-bad-data = %{version}-%{release}
Requires: gst-plugins-bad-lib = %{version}-%{release}
Requires: gst-plugins-bad-license = %{version}-%{release}
Requires: gst-plugins-bad-locales = %{version}-%{release}
Requires: libsrtp
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Tools
BuildRequires : bluez-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : curl-dev
BuildRequires : glu-dev
BuildRequires : gobject-introspection-dev
BuildRequires : gstreamer-dev
BuildRequires : gtk+-dev
BuildRequires : gtk3-dev
BuildRequires : lcms2-dev
BuildRequires : libgudev-dev
BuildRequires : libpcap-dev
BuildRequires : librsvg-dev
BuildRequires : libsndfile-dev
BuildRequires : libsrtp
BuildRequires : libsrtp-dev
BuildRequires : libssh2-dev
BuildRequires : libusb-dev
BuildRequires : libva-dev
BuildRequires : libwebp-dev
BuildRequires : mediasdk-dev
BuildRequires : mesa-dev
BuildRequires : mpc-dev
BuildRequires : mpg123-dev
BuildRequires : openexr-dev
BuildRequires : opus-dev
BuildRequires : pkgconfig(avtp)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(nice)
BuildRequires : pkgconfig(openal)
BuildRequires : pkgconfig(sndfile)
BuildRequires : sbc-dev
BuildRequires : valgrind
BuildRequires : wayland-dev

%description
GStreamer 1.18.x stable series
WHAT IT IS
----------
This is GStreamer, a framework for streaming media.

%package bin
Summary: bin components for the gst-plugins-bad package.
Group: Binaries
Requires: gst-plugins-bad-data = %{version}-%{release}
Requires: gst-plugins-bad-license = %{version}-%{release}

%description bin
bin components for the gst-plugins-bad package.


%package data
Summary: data components for the gst-plugins-bad package.
Group: Data

%description data
data components for the gst-plugins-bad package.


%package dev
Summary: dev components for the gst-plugins-bad package.
Group: Development
Requires: gst-plugins-bad-lib = %{version}-%{release}
Requires: gst-plugins-bad-bin = %{version}-%{release}
Requires: gst-plugins-bad-data = %{version}-%{release}
Provides: gst-plugins-bad-devel = %{version}-%{release}
Requires: gst-plugins-bad = %{version}-%{release}

%description dev
dev components for the gst-plugins-bad package.


%package lib
Summary: lib components for the gst-plugins-bad package.
Group: Libraries
Requires: gst-plugins-bad-data = %{version}-%{release}
Requires: gst-plugins-bad-license = %{version}-%{release}

%description lib
lib components for the gst-plugins-bad package.


%package license
Summary: license components for the gst-plugins-bad package.
Group: Default

%description license
license components for the gst-plugins-bad package.


%package locales
Summary: locales components for the gst-plugins-bad package.
Group: Default

%description locales
locales components for the gst-plugins-bad package.


%prep
%setup -q -n gst-plugins-bad-1.18.5
cd %{_builddir}/gst-plugins-bad-1.18.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631204934
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dopencv=disabled \
-Dwpe=disabled \
-Dvdpau=disabled \
-Dexamples=disabled  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gst-plugins-bad
cp %{_builddir}/gst-plugins-bad-1.18.5/COPYING %{buildroot}/usr/share/package-licenses/gst-plugins-bad/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/gst-plugins-bad-1.18.5/docs/random/LICENSE %{buildroot}/usr/share/package-licenses/gst-plugins-bad/22990b105a08bb838c95fcc4bc5450c6dfdc79ac
cp %{_builddir}/gst-plugins-bad-1.18.5/ext/sctp/usrsctp/LICENSE.md %{buildroot}/usr/share/package-licenses/gst-plugins-bad/065e53e772f604ccf39b435c4bc791d942279064
cp %{_builddir}/gst-plugins-bad-1.18.5/gst-libs/gst/codecparsers/dboolhuff.LICENSE %{buildroot}/usr/share/package-licenses/gst-plugins-bad/4dbe7c1f3a1833a88333a7c282119323e9ef44fa
cp %{_builddir}/gst-plugins-bad-1.18.5/gst/dvbsubenc/libimagequant/COPYRIGHT %{buildroot}/usr/share/package-licenses/gst-plugins-bad/5b574b9029338b80cc6df610d503db509d783ec8
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gst-plugins-bad-1.0

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gst-transcoder-1.0

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GstBadAudio-1.0.typelib
/usr/lib64/girepository-1.0/GstCodecs-1.0.typelib
/usr/lib64/girepository-1.0/GstInsertBin-1.0.typelib
/usr/lib64/girepository-1.0/GstMpegts-1.0.typelib
/usr/lib64/girepository-1.0/GstPlayer-1.0.typelib
/usr/lib64/girepository-1.0/GstTranscoder-1.0.typelib
/usr/lib64/girepository-1.0/GstWebRTC-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/gstreamer-1.0/encoding-profiles/device/dvd.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/avi.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/flv.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/mkv.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/mp3.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/mp4.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/oga.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/ogv.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/webm.gep
/usr/share/gstreamer-1.0/encoding-profiles/online-services/youtube.gep
/usr/share/gstreamer-1.0/presets/GstFreeverb.prs

%files dev
%defattr(-,root,root,-)
/usr/include/gstreamer-1.0/gst/audio/audio-bad-prelude.h
/usr/include/gstreamer-1.0/gst/audio/gstnonstreamaudiodecoder.h
/usr/include/gstreamer-1.0/gst/audio/gstplanaraudioadapter.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/basecamerabinsrc-prelude.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstbasecamerasrc.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstcamerabin-enum.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstcamerabinpreview.h
/usr/include/gstreamer-1.0/gst/codecparsers/codecparsers-prelude.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstav1parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gsth264parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gsth265parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstjpeg2000sampling.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstjpegparser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpeg4parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpegvideometa.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpegvideoparser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvc1parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp8parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp8rangedecoder.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp9parser.h
/usr/include/gstreamer-1.0/gst/insertbin/gstinsertbin.h
/usr/include/gstreamer-1.0/gst/interfaces/photography-enumtypes.h
/usr/include/gstreamer-1.0/gst/interfaces/photography-prelude.h
/usr/include/gstreamer-1.0/gst/interfaces/photography.h
/usr/include/gstreamer-1.0/gst/isoff/gstisoff.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-atsc-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-dvb-descriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-dvb-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-scte-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegts-enumtypes.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegtsdescriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegtssection.h
/usr/include/gstreamer-1.0/gst/mpegts/mpegts-prelude.h
/usr/include/gstreamer-1.0/gst/mpegts/mpegts.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-g-main-context-signal-dispatcher.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-media-info.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-signal-dispatcher.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-types.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-video-overlay-video-renderer.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-video-renderer.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-visualization.h
/usr/include/gstreamer-1.0/gst/player/gstplayer.h
/usr/include/gstreamer-1.0/gst/player/player-prelude.h
/usr/include/gstreamer-1.0/gst/player/player.h
/usr/include/gstreamer-1.0/gst/sctp/sctp-prelude.h
/usr/include/gstreamer-1.0/gst/sctp/sctpreceivemeta.h
/usr/include/gstreamer-1.0/gst/sctp/sctpsendmeta.h
/usr/include/gstreamer-1.0/gst/transcoder/gsttranscoder.h
/usr/include/gstreamer-1.0/gst/transcoder/transcoder-prelude.h
/usr/include/gstreamer-1.0/gst/uridownloader/gstfragment.h
/usr/include/gstreamer-1.0/gst/uridownloader/gsturidownloader.h
/usr/include/gstreamer-1.0/gst/uridownloader/gsturidownloader_debug.h
/usr/include/gstreamer-1.0/gst/uridownloader/uridownloader-prelude.h
/usr/include/gstreamer-1.0/gst/webrtc/datachannel.h
/usr/include/gstreamer-1.0/gst/webrtc/dtlstransport.h
/usr/include/gstreamer-1.0/gst/webrtc/icetransport.h
/usr/include/gstreamer-1.0/gst/webrtc/rtcsessiondescription.h
/usr/include/gstreamer-1.0/gst/webrtc/rtpreceiver.h
/usr/include/gstreamer-1.0/gst/webrtc/rtpsender.h
/usr/include/gstreamer-1.0/gst/webrtc/rtptransceiver.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc-enumtypes.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc_fwd.h
/usr/lib64/libgstadaptivedemux-1.0.so
/usr/lib64/libgstbadaudio-1.0.so
/usr/lib64/libgstbasecamerabinsrc-1.0.so
/usr/lib64/libgstcodecparsers-1.0.so
/usr/lib64/libgstcodecs-1.0.so
/usr/lib64/libgstinsertbin-1.0.so
/usr/lib64/libgstisoff-1.0.so
/usr/lib64/libgstmpegts-1.0.so
/usr/lib64/libgstphotography-1.0.so
/usr/lib64/libgstplayer-1.0.so
/usr/lib64/libgstsctp-1.0.so
/usr/lib64/libgsttranscoder-1.0.so
/usr/lib64/libgsturidownloader-1.0.so
/usr/lib64/libgstwayland-1.0.so
/usr/lib64/libgstwebrtc-1.0.so
/usr/lib64/pkgconfig/gstreamer-bad-audio-1.0.pc
/usr/lib64/pkgconfig/gstreamer-codecparsers-1.0.pc
/usr/lib64/pkgconfig/gstreamer-insertbin-1.0.pc
/usr/lib64/pkgconfig/gstreamer-mpegts-1.0.pc
/usr/lib64/pkgconfig/gstreamer-photography-1.0.pc
/usr/lib64/pkgconfig/gstreamer-player-1.0.pc
/usr/lib64/pkgconfig/gstreamer-plugins-bad-1.0.pc
/usr/lib64/pkgconfig/gstreamer-sctp-1.0.pc
/usr/lib64/pkgconfig/gstreamer-transcoder-1.0.pc
/usr/lib64/pkgconfig/gstreamer-webrtc-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstaccurip.so
/usr/lib64/gstreamer-1.0/libgstadpcmdec.so
/usr/lib64/gstreamer-1.0/libgstadpcmenc.so
/usr/lib64/gstreamer-1.0/libgstaiff.so
/usr/lib64/gstreamer-1.0/libgstasfmux.so
/usr/lib64/gstreamer-1.0/libgstaudiobuffersplit.so
/usr/lib64/gstreamer-1.0/libgstaudiofxbad.so
/usr/lib64/gstreamer-1.0/libgstaudiolatency.so
/usr/lib64/gstreamer-1.0/libgstaudiomixmatrix.so
/usr/lib64/gstreamer-1.0/libgstaudiovisualizers.so
/usr/lib64/gstreamer-1.0/libgstautoconvert.so
/usr/lib64/gstreamer-1.0/libgstavtp.so
/usr/lib64/gstreamer-1.0/libgstbayer.so
/usr/lib64/gstreamer-1.0/libgstbluez.so
/usr/lib64/gstreamer-1.0/libgstbz2.so
/usr/lib64/gstreamer-1.0/libgstcamerabin.so
/usr/lib64/gstreamer-1.0/libgstclosedcaption.so
/usr/lib64/gstreamer-1.0/libgstcoloreffects.so
/usr/lib64/gstreamer-1.0/libgstcolormanagement.so
/usr/lib64/gstreamer-1.0/libgstcurl.so
/usr/lib64/gstreamer-1.0/libgstdash.so
/usr/lib64/gstreamer-1.0/libgstdebugutilsbad.so
/usr/lib64/gstreamer-1.0/libgstdecklink.so
/usr/lib64/gstreamer-1.0/libgstdtls.so
/usr/lib64/gstreamer-1.0/libgstdvb.so
/usr/lib64/gstreamer-1.0/libgstdvbsubenc.so
/usr/lib64/gstreamer-1.0/libgstdvbsuboverlay.so
/usr/lib64/gstreamer-1.0/libgstdvdspu.so
/usr/lib64/gstreamer-1.0/libgstfaceoverlay.so
/usr/lib64/gstreamer-1.0/libgstfbdevsink.so
/usr/lib64/gstreamer-1.0/libgstfestival.so
/usr/lib64/gstreamer-1.0/libgstfieldanalysis.so
/usr/lib64/gstreamer-1.0/libgstfreeverb.so
/usr/lib64/gstreamer-1.0/libgstfrei0r.so
/usr/lib64/gstreamer-1.0/libgstgaudieffects.so
/usr/lib64/gstreamer-1.0/libgstgdp.so
/usr/lib64/gstreamer-1.0/libgstgeometrictransform.so
/usr/lib64/gstreamer-1.0/libgsthls.so
/usr/lib64/gstreamer-1.0/libgstid3tag.so
/usr/lib64/gstreamer-1.0/libgstinter.so
/usr/lib64/gstreamer-1.0/libgstinterlace.so
/usr/lib64/gstreamer-1.0/libgstipcpipeline.so
/usr/lib64/gstreamer-1.0/libgstivfparse.so
/usr/lib64/gstreamer-1.0/libgstivtc.so
/usr/lib64/gstreamer-1.0/libgstjp2kdecimator.so
/usr/lib64/gstreamer-1.0/libgstjpegformat.so
/usr/lib64/gstreamer-1.0/libgstkms.so
/usr/lib64/gstreamer-1.0/libgstlegacyrawparse.so
/usr/lib64/gstreamer-1.0/libgstmidi.so
/usr/lib64/gstreamer-1.0/libgstmpegpsdemux.so
/usr/lib64/gstreamer-1.0/libgstmpegpsmux.so
/usr/lib64/gstreamer-1.0/libgstmpegtsdemux.so
/usr/lib64/gstreamer-1.0/libgstmpegtsmux.so
/usr/lib64/gstreamer-1.0/libgstmsdk.so
/usr/lib64/gstreamer-1.0/libgstmxf.so
/usr/lib64/gstreamer-1.0/libgstnetsim.so
/usr/lib64/gstreamer-1.0/libgstnvcodec.so
/usr/lib64/gstreamer-1.0/libgstopenal.so
/usr/lib64/gstreamer-1.0/libgstopenexr.so
/usr/lib64/gstreamer-1.0/libgstopusparse.so
/usr/lib64/gstreamer-1.0/libgstpcapparse.so
/usr/lib64/gstreamer-1.0/libgstpnm.so
/usr/lib64/gstreamer-1.0/libgstproxy.so
/usr/lib64/gstreamer-1.0/libgstremovesilence.so
/usr/lib64/gstreamer-1.0/libgstrfbsrc.so
/usr/lib64/gstreamer-1.0/libgstrist.so
/usr/lib64/gstreamer-1.0/libgstrsvg.so
/usr/lib64/gstreamer-1.0/libgstrtmp2.so
/usr/lib64/gstreamer-1.0/libgstrtpmanagerbad.so
/usr/lib64/gstreamer-1.0/libgstrtponvif.so
/usr/lib64/gstreamer-1.0/libgstsbc.so
/usr/lib64/gstreamer-1.0/libgstsctp.so
/usr/lib64/gstreamer-1.0/libgstsdpelem.so
/usr/lib64/gstreamer-1.0/libgstsegmentclip.so
/usr/lib64/gstreamer-1.0/libgstshm.so
/usr/lib64/gstreamer-1.0/libgstsiren.so
/usr/lib64/gstreamer-1.0/libgstsmooth.so
/usr/lib64/gstreamer-1.0/libgstsmoothstreaming.so
/usr/lib64/gstreamer-1.0/libgstsndfile.so
/usr/lib64/gstreamer-1.0/libgstspeed.so
/usr/lib64/gstreamer-1.0/libgstsrtp.so
/usr/lib64/gstreamer-1.0/libgstsubenc.so
/usr/lib64/gstreamer-1.0/libgstswitchbin.so
/usr/lib64/gstreamer-1.0/libgsttimecode.so
/usr/lib64/gstreamer-1.0/libgsttranscode.so
/usr/lib64/gstreamer-1.0/libgstttmlsubs.so
/usr/lib64/gstreamer-1.0/libgstuvch264.so
/usr/lib64/gstreamer-1.0/libgstv4l2codecs.so
/usr/lib64/gstreamer-1.0/libgstva.so
/usr/lib64/gstreamer-1.0/libgstvideofiltersbad.so
/usr/lib64/gstreamer-1.0/libgstvideoframe_audiolevel.so
/usr/lib64/gstreamer-1.0/libgstvideoparsersbad.so
/usr/lib64/gstreamer-1.0/libgstvideosignal.so
/usr/lib64/gstreamer-1.0/libgstvmnc.so
/usr/lib64/gstreamer-1.0/libgstwaylandsink.so
/usr/lib64/gstreamer-1.0/libgstwebp.so
/usr/lib64/gstreamer-1.0/libgstwebrtc.so
/usr/lib64/gstreamer-1.0/libgsty4mdec.so
/usr/lib64/libgstadaptivedemux-1.0.so.0
/usr/lib64/libgstadaptivedemux-1.0.so.0.1805.0
/usr/lib64/libgstbadaudio-1.0.so.0
/usr/lib64/libgstbadaudio-1.0.so.0.1805.0
/usr/lib64/libgstbasecamerabinsrc-1.0.so.0
/usr/lib64/libgstbasecamerabinsrc-1.0.so.0.1805.0
/usr/lib64/libgstcodecparsers-1.0.so.0
/usr/lib64/libgstcodecparsers-1.0.so.0.1805.0
/usr/lib64/libgstcodecs-1.0.so.0
/usr/lib64/libgstcodecs-1.0.so.0.1805.0
/usr/lib64/libgstinsertbin-1.0.so.0
/usr/lib64/libgstinsertbin-1.0.so.0.1805.0
/usr/lib64/libgstisoff-1.0.so.0
/usr/lib64/libgstisoff-1.0.so.0.1805.0
/usr/lib64/libgstmpegts-1.0.so.0
/usr/lib64/libgstmpegts-1.0.so.0.1805.0
/usr/lib64/libgstphotography-1.0.so.0
/usr/lib64/libgstphotography-1.0.so.0.1805.0
/usr/lib64/libgstplayer-1.0.so.0
/usr/lib64/libgstplayer-1.0.so.0.1805.0
/usr/lib64/libgstsctp-1.0.so.0
/usr/lib64/libgstsctp-1.0.so.0.1805.0
/usr/lib64/libgsttranscoder-1.0.so.0
/usr/lib64/libgsturidownloader-1.0.so.0
/usr/lib64/libgsturidownloader-1.0.so.0.1805.0
/usr/lib64/libgstwayland-1.0.so.0
/usr/lib64/libgstwayland-1.0.so.0.1805.0
/usr/lib64/libgstwebrtc-1.0.so.0
/usr/lib64/libgstwebrtc-1.0.so.0.1805.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gst-plugins-bad/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/gst-plugins-bad/065e53e772f604ccf39b435c4bc791d942279064
/usr/share/package-licenses/gst-plugins-bad/22990b105a08bb838c95fcc4bc5450c6dfdc79ac
/usr/share/package-licenses/gst-plugins-bad/4dbe7c1f3a1833a88333a7c282119323e9ef44fa
/usr/share/package-licenses/gst-plugins-bad/5b574b9029338b80cc6df610d503db509d783ec8

%files locales -f gst-plugins-bad-1.0.lang
%defattr(-,root,root,-)

