#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x0668CC1486C2D7B5 (slomo@debian.org)
#
Name     : gst-plugins-bad
Version  : 1.12.3
Release  : 35
URL      : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.12.3.tar.xz
Source0  : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.12.3.tar.xz
Source99 : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.12.3.tar.xz.asc
Summary  : GStreamer Wayland support
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.0
Requires: gst-plugins-bad-data
Requires: gst-plugins-bad-lib
Requires: gst-plugins-bad-doc
Requires: gst-plugins-bad-locales
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bluez-dev
BuildRequires : bzip2-dev
BuildRequires : docbook-xml
BuildRequires : gettext-bin
BuildRequires : glu-dev
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk+-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : gtk3-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libusb-dev
BuildRequires : libxslt-bin
BuildRequires : m4
BuildRequires : mesa-dev
BuildRequires : meson
BuildRequires : mpg123-dev
BuildRequires : ninja
BuildRequires : opencv-dev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(clutter-1.0)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gstreamer-allocators-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(openal)
BuildRequires : pkgconfig(opencv)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(sdl)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : python3
BuildRequires : sbc-dev
BuildRequires : valgrind
BuildRequires : vulkan-sdk-dev
BuildRequires : wayland-dev
Patch1: 0001-disable-gst-segementation-plugin.patch
Patch2: 0002-Disable-request-by-bgsegm.hpp.patch
Patch3: 0003-opencv-Update-version-for-building-plugins.patch

%description
GStreamer 1.12.x stable series
WHAT IT IS
----------
This is GStreamer, a framework for streaming media.

%package data
Summary: data components for the gst-plugins-bad package.
Group: Data

%description data
data components for the gst-plugins-bad package.


%package dev
Summary: dev components for the gst-plugins-bad package.
Group: Development
Requires: gst-plugins-bad-lib
Requires: gst-plugins-bad-data
Provides: gst-plugins-bad-devel

%description dev
dev components for the gst-plugins-bad package.


%package doc
Summary: doc components for the gst-plugins-bad package.
Group: Documentation

%description doc
doc components for the gst-plugins-bad package.


%package lib
Summary: lib components for the gst-plugins-bad package.
Group: Libraries
Requires: gst-plugins-bad-data

%description lib
lib components for the gst-plugins-bad package.


%package locales
Summary: locales components for the gst-plugins-bad package.
Group: Default

%description locales
locales components for the gst-plugins-bad package.


%prep
%setup -q -n gst-plugins-bad-1.12.3
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510347592
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
%reconfigure --disable-static --enable-opencv
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1510347592
rm -rf %{buildroot}
%make_install
%find_lang gst-plugins-bad-1.0

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GstBadAllocators-1.0.typelib
/usr/lib64/girepository-1.0/GstGL-1.0.typelib
/usr/lib64/girepository-1.0/GstInsertBin-1.0.typelib
/usr/lib64/girepository-1.0/GstMpegts-1.0.typelib
/usr/lib64/girepository-1.0/GstPlayer-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/gst-plugins-bad/1.0/opencv_haarcascades/fist.xml
/usr/share/gst-plugins-bad/1.0/opencv_haarcascades/palm.xml
/usr/share/gstreamer-1.0/presets/GstFreeverb.prs

%files dev
%defattr(-,root,root,-)
/usr/include/gstreamer-1.0/gst/allocators/badallocators.h
/usr/include/gstreamer-1.0/gst/allocators/gstphysmemory.h
/usr/include/gstreamer-1.0/gst/audio/gstaudioaggregator.h
/usr/include/gstreamer-1.0/gst/base/gstaggregator.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstbasecamerasrc.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstcamerabin-enum.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstcamerabinpreview.h
/usr/include/gstreamer-1.0/gst/codecparsers/gsth264parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gsth265parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstjpeg2000sampling.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstjpegparser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpeg4parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpegvideometa.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpegvideoparser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvc1parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp8parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp8rangedecoder.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp9parser.h
/usr/include/gstreamer-1.0/gst/gl/egl/gstegl.h
/usr/include/gstreamer-1.0/gst/gl/egl/gsteglimage.h
/usr/include/gstreamer-1.0/gst/gl/egl/gstgldisplay_egl.h
/usr/include/gstreamer-1.0/gst/gl/egl/gstglmemoryegl.h
/usr/include/gstreamer-1.0/gst/gl/gl.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/all_functions.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/base.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/blending.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/buffers.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/debug.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/eglimage.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/fbo.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/fixedfunction.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/gles.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/gstgl_compat.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/gstgl_gles2compat.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/opengl.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/query.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/shaders.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/sync.h
/usr/include/gstreamer-1.0/gst/gl/glprototypes/vao.h
/usr/include/gstreamer-1.0/gst/gl/gstgl_enums.h
/usr/include/gstreamer-1.0/gst/gl/gstgl_fwd.h
/usr/include/gstreamer-1.0/gst/gl/gstglapi.h
/usr/include/gstreamer-1.0/gst/gl/gstglbasefilter.h
/usr/include/gstreamer-1.0/gst/gl/gstglbasememory.h
/usr/include/gstreamer-1.0/gst/gl/gstglbuffer.h
/usr/include/gstreamer-1.0/gst/gl/gstglbufferpool.h
/usr/include/gstreamer-1.0/gst/gl/gstglcolorconvert.h
/usr/include/gstreamer-1.0/gst/gl/gstglcontext.h
/usr/include/gstreamer-1.0/gst/gl/gstgldebug.h
/usr/include/gstreamer-1.0/gst/gl/gstgldisplay.h
/usr/include/gstreamer-1.0/gst/gl/gstglfeature.h
/usr/include/gstreamer-1.0/gst/gl/gstglfilter.h
/usr/include/gstreamer-1.0/gst/gl/gstglformat.h
/usr/include/gstreamer-1.0/gst/gl/gstglframebuffer.h
/usr/include/gstreamer-1.0/gst/gl/gstglmemory.h
/usr/include/gstreamer-1.0/gst/gl/gstglmemorypbo.h
/usr/include/gstreamer-1.0/gst/gl/gstgloverlaycompositor.h
/usr/include/gstreamer-1.0/gst/gl/gstglquery.h
/usr/include/gstreamer-1.0/gst/gl/gstglrenderbuffer.h
/usr/include/gstreamer-1.0/gst/gl/gstglshader.h
/usr/include/gstreamer-1.0/gst/gl/gstglshaderstrings.h
/usr/include/gstreamer-1.0/gst/gl/gstglsl.h
/usr/include/gstreamer-1.0/gst/gl/gstglslstage.h
/usr/include/gstreamer-1.0/gst/gl/gstglsyncmeta.h
/usr/include/gstreamer-1.0/gst/gl/gstglupload.h
/usr/include/gstreamer-1.0/gst/gl/gstglutils.h
/usr/include/gstreamer-1.0/gst/gl/gstglviewconvert.h
/usr/include/gstreamer-1.0/gst/gl/gstglwindow.h
/usr/include/gstreamer-1.0/gst/gl/wayland/gstgldisplay_wayland.h
/usr/include/gstreamer-1.0/gst/gl/x11/gstgldisplay_x11.h
/usr/include/gstreamer-1.0/gst/insertbin/gstinsertbin.h
/usr/include/gstreamer-1.0/gst/interfaces/photography-enumtypes.h
/usr/include/gstreamer-1.0/gst/interfaces/photography.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-atsc-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-dvb-descriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-dvb-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-scte-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegts-enumtypes.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegtsdescriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegtssection.h
/usr/include/gstreamer-1.0/gst/mpegts/mpegts.h
/usr/include/gstreamer-1.0/gst/opencv/gstopencvutils.h
/usr/include/gstreamer-1.0/gst/opencv/gstopencvvideofilter.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-g-main-context-signal-dispatcher.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-media-info.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-signal-dispatcher.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-types.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-video-overlay-video-renderer.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-video-renderer.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-visualization.h
/usr/include/gstreamer-1.0/gst/player/gstplayer.h
/usr/include/gstreamer-1.0/gst/player/player.h
/usr/include/gstreamer-1.0/gst/uridownloader/gstfragment.h
/usr/include/gstreamer-1.0/gst/uridownloader/gsturidownloader.h
/usr/include/gstreamer-1.0/gst/uridownloader/gsturidownloader_debug.h
/usr/include/gstreamer-1.0/gst/video/gstvideoaggregator.h
/usr/include/gstreamer-1.0/gst/video/gstvideoaggregatorpad.h
/usr/lib64/gstreamer-1.0/include/gst/gl/gstglconfig.h
/usr/lib64/libgstadaptivedemux-1.0.so
/usr/lib64/libgstbadallocators-1.0.so
/usr/lib64/libgstbadaudio-1.0.so
/usr/lib64/libgstbadbase-1.0.so
/usr/lib64/libgstbadvideo-1.0.so
/usr/lib64/libgstbasecamerabinsrc-1.0.so
/usr/lib64/libgstcodecparsers-1.0.so
/usr/lib64/libgstgl-1.0.so
/usr/lib64/libgstinsertbin-1.0.so
/usr/lib64/libgstmpegts-1.0.so
/usr/lib64/libgstopencv-1.0.so
/usr/lib64/libgstphotography-1.0.so
/usr/lib64/libgstplayer-1.0.so
/usr/lib64/libgsturidownloader-1.0.so
/usr/lib64/libgstwayland-1.0.so
/usr/lib64/pkgconfig/gstreamer-bad-allocators-1.0.pc
/usr/lib64/pkgconfig/gstreamer-bad-audio-1.0.pc
/usr/lib64/pkgconfig/gstreamer-bad-base-1.0.pc
/usr/lib64/pkgconfig/gstreamer-bad-video-1.0.pc
/usr/lib64/pkgconfig/gstreamer-codecparsers-1.0.pc
/usr/lib64/pkgconfig/gstreamer-gl-1.0.pc
/usr/lib64/pkgconfig/gstreamer-insertbin-1.0.pc
/usr/lib64/pkgconfig/gstreamer-mpegts-1.0.pc
/usr/lib64/pkgconfig/gstreamer-player-1.0.pc
/usr/lib64/pkgconfig/gstreamer-plugins-bad-1.0.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstAggregator.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstAggregatorPad.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLBaseFilter.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLBufferPool.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLColorConvert.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLContext.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLDisplay.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLFilter.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLFramebuffer.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLSLStage.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLShader.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLUpload.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLViewConvert.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstGLWindow.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstPlayer.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstPlayerMediaInfo.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstPlayerVideoOverlayVideoRenderer.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstPlayerVisualization.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstVideoAggregator.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/GstVideoAggregatorPad.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/annotation-glossary.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/api-index-deprecated.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/api-index-full.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/base.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/ch08.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/codecparsers.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/compiling.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gl.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-1.0.devhelp2
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-ATSC-variants-of-MPEG-TS-descriptors.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-ATSC-variants-of-MPEG-TS-sections.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-Base-MPEG-TS-descriptors.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-Base-MPEG-TS-sections.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-DVB-variants-of-MPEG-TS-descriptors.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-DVB-variants-of-MPEG-TS-sections.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstEGLImage.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLAPI.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLBuffer.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLDisplayWayland.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLDisplayX11.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLMemory.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLMemoryPBO.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLOverlayCompositor.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLQuery.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLRenderbuffer.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLSL.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGLSyncMeta.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstGlBaseMemory.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstInsertbin.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstPhotography.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-GstPlayerGMainContextSignalDispatcher.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-ISDB-variants-of-MPEG-TS-descriptors.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-Mpeg-ts-helper-library.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-OpenGL-Formats.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-OpenGL-Miscellaneous-Utilities.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-OpenGL-debugging.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-gstglmemoryegl.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-gstmpegvideometa.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-h264parser.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-jpegparser.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-mpeg4parser.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-mpegvideoparser.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gst-plugins-bad-libs-vc1parser.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gstreamer-libs-hierarchy.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/gstreamer-plugins-bad.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/home.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/index.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/left-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/left.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/mpegts.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/player.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/right-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/right.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/style.css
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/tools.html
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/up-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/up.png
/usr/share/gtk-doc/html/gst-plugins-bad-libs-1.0/video.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/camerabin.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/ch01.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/ch02.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-1.0.devhelp2
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-IQA.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-accurip.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-aiffmux.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-aiffparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-assrender.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-audiointerleave.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-audiomixer.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-audioparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-autoconvert.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-bs2b.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-bulge.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-burn.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-camerabin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-chromium.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-circle.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-coloreffects.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-compositor.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-cvdilate.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-cvequalizehist.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-cverode.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-cvlaplace.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-cvsmooth.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-cvsobel.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-diffuse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-dilate.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-dodge.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-dtmfdetect.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-dtsdec.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-dvbsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-dvdspu.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-edgedetect.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-exclusion.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-faac.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-faad.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-faceblur.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-facedetect.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-festival.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-fisheye.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-fpsdisplaysink.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gaussianblur.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glcolorbalance.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glcolorconvert.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glcolorscale.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gldeinterlace.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gldifferencematte.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gldownload.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-blur.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-bulge.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-fisheye.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-glow.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-heat.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-identity.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-laplacian.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-lumaxpro.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-mirror.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-sepia.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-sin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-sobel.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-square.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-squeeze.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-stretch.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-tunnel.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-twirl.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-xpro.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects-xray.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gleffects.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glfilterapp.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glfilterbin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glfiltercube.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glfilterglass.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glimagesink.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glimagesinkelement.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glmixerbin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glmosaic.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gloverlay.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glshader.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glsinkbin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glsrcbin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glstereomix.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glstereosplit.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gltestsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-gltransformation.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glupload.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glvideomixer.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glvideomixerelement.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-glviewconvert.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-jpegparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-kaleidoscope.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-liveadder.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-marble.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mimdec.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mimenc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mirror.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-modplug.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mpeg2enc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mpegpsmux.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mpegtsmux.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-mplex.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-neonhttpsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-ofa.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-openalsink.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-openalsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-opencvtextoverlay.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-pcapparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-pinch.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-aiff.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-assrender.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-audiomixer.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-audiovisualizers.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-autoconvert.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-bayer.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-bs2b.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-bz2.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-camerabin.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-coloreffects.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-curl.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-debugutilsbad.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-dtsdec.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-dvb.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-dvdspu.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-faac.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-faad.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-festival.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-gaudieffects.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-geometrictransform.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-gsm.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-jpegformat.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-mms.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-modplug.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-mpeg2enc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-mpegpsmux.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-mpegtsmux.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-mplex.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-neon.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-ofa.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-openal.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-opencv.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-opengl.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-pcapparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-rawparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-rfbsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-rtmp.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-sdpelem.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-shm.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-soundtouch.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-speed.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-ttmlsubs.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-voaacenc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-voamrwbenc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-webrtcdsp.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-plugin-zbar.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-rawaudioparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-rawvideoparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-rfbsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-rtmpsink.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-rtmpsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-sdpdemux.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-shmsink.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-shmsrc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-solarize.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-spacescope.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-spectrascope.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-speed.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-sphere.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-square.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-stretch.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-synaescope.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-templatematch.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-ttmlparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-ttmlrender.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-tunnel.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-twirl.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-unalignedaudioparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-unalignedvideoparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-videoparse.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-voaacenc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-voamrwbenc.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-waterripple.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-wavescope.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-webrtcdsp.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-webrtcechoprobe.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/gst-plugins-bad-plugins-zbar.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/home.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/index.html
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/left-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/left.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/right-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/right.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/style.css
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/up-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-bad-plugins-1.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstaccurip.so
/usr/lib64/gstreamer-1.0/libgstadpcmdec.so
/usr/lib64/gstreamer-1.0/libgstadpcmenc.so
/usr/lib64/gstreamer-1.0/libgstaiff.so
/usr/lib64/gstreamer-1.0/libgstasfmux.so
/usr/lib64/gstreamer-1.0/libgstaudiobuffersplit.so
/usr/lib64/gstreamer-1.0/libgstaudiofxbad.so
/usr/lib64/gstreamer-1.0/libgstaudiomixer.so
/usr/lib64/gstreamer-1.0/libgstaudiomixmatrix.so
/usr/lib64/gstreamer-1.0/libgstaudiovisualizers.so
/usr/lib64/gstreamer-1.0/libgstautoconvert.so
/usr/lib64/gstreamer-1.0/libgstbayer.so
/usr/lib64/gstreamer-1.0/libgstbluez.so
/usr/lib64/gstreamer-1.0/libgstbz2.so
/usr/lib64/gstreamer-1.0/libgstcamerabin.so
/usr/lib64/gstreamer-1.0/libgstcoloreffects.so
/usr/lib64/gstreamer-1.0/libgstcompositor.so
/usr/lib64/gstreamer-1.0/libgstcurl.so
/usr/lib64/gstreamer-1.0/libgstdashdemux.so
/usr/lib64/gstreamer-1.0/libgstdebugutilsbad.so
/usr/lib64/gstreamer-1.0/libgstdecklink.so
/usr/lib64/gstreamer-1.0/libgstdtls.so
/usr/lib64/gstreamer-1.0/libgstdvb.so
/usr/lib64/gstreamer-1.0/libgstdvbsuboverlay.so
/usr/lib64/gstreamer-1.0/libgstdvdspu.so
/usr/lib64/gstreamer-1.0/libgstfaceoverlay.so
/usr/lib64/gstreamer-1.0/libgstfbdevsink.so
/usr/lib64/gstreamer-1.0/libgstfestival.so
/usr/lib64/gstreamer-1.0/libgstfieldanalysis.so
/usr/lib64/gstreamer-1.0/libgstfreeverb.so
/usr/lib64/gstreamer-1.0/libgstfrei0r.so
/usr/lib64/gstreamer-1.0/libgstgaudieffects.so
/usr/lib64/gstreamer-1.0/libgstgdp.so
/usr/lib64/gstreamer-1.0/libgstgeometrictransform.so
/usr/lib64/gstreamer-1.0/libgstgtk.so
/usr/lib64/gstreamer-1.0/libgsthls.so
/usr/lib64/gstreamer-1.0/libgstid3tag.so
/usr/lib64/gstreamer-1.0/libgstinter.so
/usr/lib64/gstreamer-1.0/libgstinterlace.so
/usr/lib64/gstreamer-1.0/libgstivfparse.so
/usr/lib64/gstreamer-1.0/libgstivtc.so
/usr/lib64/gstreamer-1.0/libgstjp2kdecimator.so
/usr/lib64/gstreamer-1.0/libgstjpegformat.so
/usr/lib64/gstreamer-1.0/libgstkms.so
/usr/lib64/gstreamer-1.0/libgstlegacyrawparse.so
/usr/lib64/gstreamer-1.0/libgstmidi.so
/usr/lib64/gstreamer-1.0/libgstmpegpsdemux.so
/usr/lib64/gstreamer-1.0/libgstmpegpsmux.so
/usr/lib64/gstreamer-1.0/libgstmpegtsdemux.so
/usr/lib64/gstreamer-1.0/libgstmpegtsmux.so
/usr/lib64/gstreamer-1.0/libgstmxf.so
/usr/lib64/gstreamer-1.0/libgstnetsim.so
/usr/lib64/gstreamer-1.0/libgstopenal.so
/usr/lib64/gstreamer-1.0/libgstopencv.so
/usr/lib64/gstreamer-1.0/libgstopengl.so
/usr/lib64/gstreamer-1.0/libgstpcapparse.so
/usr/lib64/gstreamer-1.0/libgstpnm.so
/usr/lib64/gstreamer-1.0/libgstremovesilence.so
/usr/lib64/gstreamer-1.0/libgstrfbsrc.so
/usr/lib64/gstreamer-1.0/libgstrsvg.so
/usr/lib64/gstreamer-1.0/libgstrtponvif.so
/usr/lib64/gstreamer-1.0/libgstsbc.so
/usr/lib64/gstreamer-1.0/libgstsdpelem.so
/usr/lib64/gstreamer-1.0/libgstsegmentclip.so
/usr/lib64/gstreamer-1.0/libgstshm.so
/usr/lib64/gstreamer-1.0/libgstsiren.so
/usr/lib64/gstreamer-1.0/libgstsmooth.so
/usr/lib64/gstreamer-1.0/libgstsmoothstreaming.so
/usr/lib64/gstreamer-1.0/libgstsndfile.so
/usr/lib64/gstreamer-1.0/libgstspeed.so
/usr/lib64/gstreamer-1.0/libgststereo.so
/usr/lib64/gstreamer-1.0/libgstsubenc.so
/usr/lib64/gstreamer-1.0/libgsttimecode.so
/usr/lib64/gstreamer-1.0/libgstttmlsubs.so
/usr/lib64/gstreamer-1.0/libgstvcdsrc.so
/usr/lib64/gstreamer-1.0/libgstvideofiltersbad.so
/usr/lib64/gstreamer-1.0/libgstvideoframe_audiolevel.so
/usr/lib64/gstreamer-1.0/libgstvideoparsersbad.so
/usr/lib64/gstreamer-1.0/libgstvideosignal.so
/usr/lib64/gstreamer-1.0/libgstvmnc.so
/usr/lib64/gstreamer-1.0/libgstwaylandsink.so
/usr/lib64/gstreamer-1.0/libgstwebp.so
/usr/lib64/gstreamer-1.0/libgsty4mdec.so
/usr/lib64/gstreamer-1.0/libgstyadif.so
/usr/lib64/libgstadaptivedemux-1.0.so.0
/usr/lib64/libgstadaptivedemux-1.0.so.0.1203.0
/usr/lib64/libgstbadallocators-1.0.so.0
/usr/lib64/libgstbadallocators-1.0.so.0.1203.0
/usr/lib64/libgstbadaudio-1.0.so.0
/usr/lib64/libgstbadaudio-1.0.so.0.1203.0
/usr/lib64/libgstbadbase-1.0.so.0
/usr/lib64/libgstbadbase-1.0.so.0.1203.0
/usr/lib64/libgstbadvideo-1.0.so.0
/usr/lib64/libgstbadvideo-1.0.so.0.1203.0
/usr/lib64/libgstbasecamerabinsrc-1.0.so.0
/usr/lib64/libgstbasecamerabinsrc-1.0.so.0.1203.0
/usr/lib64/libgstcodecparsers-1.0.so.0
/usr/lib64/libgstcodecparsers-1.0.so.0.1203.0
/usr/lib64/libgstgl-1.0.so.0
/usr/lib64/libgstgl-1.0.so.0.1203.0
/usr/lib64/libgstinsertbin-1.0.so.0
/usr/lib64/libgstinsertbin-1.0.so.0.1203.0
/usr/lib64/libgstmpegts-1.0.so.0
/usr/lib64/libgstmpegts-1.0.so.0.1203.0
/usr/lib64/libgstopencv-1.0.so.0
/usr/lib64/libgstopencv-1.0.so.0.1203.0
/usr/lib64/libgstphotography-1.0.so.0
/usr/lib64/libgstphotography-1.0.so.0.1203.0
/usr/lib64/libgstplayer-1.0.so.0
/usr/lib64/libgstplayer-1.0.so.0.1203.0
/usr/lib64/libgsturidownloader-1.0.so.0
/usr/lib64/libgsturidownloader-1.0.so.0.1203.0
/usr/lib64/libgstwayland-1.0.so.0
/usr/lib64/libgstwayland-1.0.so.0.1203.0

%files locales -f gst-plugins-bad-1.0.lang
%defattr(-,root,root,-)

