#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
# Source0 file verified with key 0x5D2EEE6F6F349D7C (tim@centricular.com)
#
Name     : gst-plugins-bad
Version  : 1.22.2
Release  : 110
URL      : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.22.2.tar.xz
Source0  : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.22.2.tar.xz
Source1  : https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.22.2.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 LGPL-2.1 MIT
Requires: gst-plugins-bad-bin = %{version}-%{release}
Requires: gst-plugins-bad-data = %{version}-%{release}
Requires: gst-plugins-bad-lib = %{version}-%{release}
Requires: gst-plugins-bad-license = %{version}-%{release}
Requires: gst-plugins-bad-locales = %{version}-%{release}
Requires: libsrtp
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Tools
BuildRequires : bluez-dev
BuildRequires : buildreq-meson
BuildRequires : curl-dev
BuildRequires : glu-dev
BuildRequires : gobject-introspection-dev
BuildRequires : gstreamer-dev
BuildRequires : gtk+-dev
BuildRequires : gtk3-dev
BuildRequires : json-glib-dev
BuildRequires : lcms2-dev
BuildRequires : libgudev-dev
BuildRequires : libpcap-dev
BuildRequires : librsvg-dev
BuildRequires : libsndfile-dev
BuildRequires : libsoup-dev
BuildRequires : libsrtp-dev
BuildRequires : libssh2-dev
BuildRequires : libusb-dev
BuildRequires : libva-dev
BuildRequires : libwebp-dev
BuildRequires : mediasdk-dev
BuildRequires : mesa-dev
BuildRequires : mpc-dev
BuildRequires : mpg123-dev
BuildRequires : openexr-dev
BuildRequires : opus-dev
BuildRequires : pkgconfig(avtp)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(libqrencode)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(nice)
BuildRequires : pkgconfig(openal)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : sbc-dev
BuildRequires : valgrind
BuildRequires : wayland-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
videoparse
==========
The videoparse element is used to parse a file containing raw image
data.

%package bin
Summary: bin components for the gst-plugins-bad package.
Group: Binaries
Requires: gst-plugins-bad-data = %{version}-%{release}
Requires: gst-plugins-bad-license = %{version}-%{release}

%description bin
bin components for the gst-plugins-bad package.


%package data
Summary: data components for the gst-plugins-bad package.
Group: Data

%description data
data components for the gst-plugins-bad package.


%package dev
Summary: dev components for the gst-plugins-bad package.
Group: Development
Requires: gst-plugins-bad-lib = %{version}-%{release}
Requires: gst-plugins-bad-bin = %{version}-%{release}
Requires: gst-plugins-bad-data = %{version}-%{release}
Provides: gst-plugins-bad-devel = %{version}-%{release}
Requires: gst-plugins-bad = %{version}-%{release}

%description dev
dev components for the gst-plugins-bad package.


%package lib
Summary: lib components for the gst-plugins-bad package.
Group: Libraries
Requires: gst-plugins-bad-data = %{version}-%{release}
Requires: gst-plugins-bad-license = %{version}-%{release}

%description lib
lib components for the gst-plugins-bad package.


%package license
Summary: license components for the gst-plugins-bad package.
Group: Default

%description license
license components for the gst-plugins-bad package.


%package locales
Summary: locales components for the gst-plugins-bad package.
Group: Default

%description locales
locales components for the gst-plugins-bad package.


%prep
%setup -q -n gst-plugins-bad-1.22.2
cd %{_builddir}/gst-plugins-bad-1.22.2
pushd ..
cp -a gst-plugins-bad-1.22.2 buildavx2
popd
pushd ..
cp -a gst-plugins-bad-1.22.2 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683226929
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dopencv=disabled \
-Dwpe=disabled \
-Dexamples=disabled  builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dopencv=disabled \
-Dwpe=disabled \
-Dexamples=disabled  builddiravx2
ninja -v -C builddiravx2
CFLAGS="$CFLAGS -m64 -march=x86-64-v4 -Wl,-z,x86-64-v4 -O3 -mprefer-vector-width=512" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v4 -Wl,-z,x86-64-v4 -mprefer-vector-width=512" LDFLAGS="$LDFLAGS -m64 -march=x86-64-v4" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dopencv=disabled \
-Dwpe=disabled \
-Dexamples=disabled  builddiravx512
ninja -v -C builddiravx512

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gst-plugins-bad
cp %{_builddir}/gst-plugins-bad-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gst-plugins-bad/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/gst-plugins-bad-%{version}/docs/random/LICENSE %{buildroot}/usr/share/package-licenses/gst-plugins-bad/22990b105a08bb838c95fcc4bc5450c6dfdc79ac || :
cp %{_builddir}/gst-plugins-bad-%{version}/ext/sctp/usrsctp/LICENSE.md %{buildroot}/usr/share/package-licenses/gst-plugins-bad/065e53e772f604ccf39b435c4bc791d942279064 || :
cp %{_builddir}/gst-plugins-bad-%{version}/gst-libs/gst/codecparsers/dboolhuff.LICENSE %{buildroot}/usr/share/package-licenses/gst-plugins-bad/4dbe7c1f3a1833a88333a7c282119323e9ef44fa || :
cp %{_builddir}/gst-plugins-bad-%{version}/gst/dvbsubenc/libimagequant/COPYRIGHT %{buildroot}/usr/share/package-licenses/gst-plugins-bad/5b574b9029338b80cc6df610d503db509d783ec8 || :
cp %{_builddir}/gst-plugins-bad-%{version}/sys/directshow/strmbase/LICENSE %{buildroot}/usr/share/package-licenses/gst-plugins-bad/da14fe4b0940c1e74ce043eddb8fc00f28516b62 || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot}-v4 ninja -C builddiravx512 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gst-plugins-bad-1.0
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gst-transcoder-1.0
/V4/usr/bin/gst-transcoder-1.0
/usr/bin/gst-transcoder-1.0

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/CudaGst-1.0.typelib
/usr/lib64/girepository-1.0/GstBadAudio-1.0.typelib
/usr/lib64/girepository-1.0/GstCodecs-1.0.typelib
/usr/lib64/girepository-1.0/GstCuda-1.0.typelib
/usr/lib64/girepository-1.0/GstInsertBin-1.0.typelib
/usr/lib64/girepository-1.0/GstMpegts-1.0.typelib
/usr/lib64/girepository-1.0/GstPlay-1.0.typelib
/usr/lib64/girepository-1.0/GstPlayer-1.0.typelib
/usr/lib64/girepository-1.0/GstTranscoder-1.0.typelib
/usr/lib64/girepository-1.0/GstVa-1.0.typelib
/usr/lib64/girepository-1.0/GstWebRTC-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/gstreamer-1.0/encoding-profiles/device/dvd.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/avi.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/flv.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/mkv.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/mp3.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/mp4.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/oga.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/ogv.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/ts.gep
/usr/share/gstreamer-1.0/encoding-profiles/file-extension/webm.gep
/usr/share/gstreamer-1.0/encoding-profiles/online-services/youtube.gep
/usr/share/gstreamer-1.0/presets/GstFreeverb.prs

%files dev
%defattr(-,root,root,-)
/V3/usr/lib64/libgstadaptivedemux-1.0.so
/V3/usr/lib64/libgstbadaudio-1.0.so
/V3/usr/lib64/libgstbasecamerabinsrc-1.0.so
/V3/usr/lib64/libgstcodecparsers-1.0.so
/V3/usr/lib64/libgstcodecs-1.0.so
/V3/usr/lib64/libgstcuda-1.0.so
/V3/usr/lib64/libgstinsertbin-1.0.so
/V3/usr/lib64/libgstisoff-1.0.so
/V3/usr/lib64/libgstmpegts-1.0.so
/V3/usr/lib64/libgstphotography-1.0.so
/V3/usr/lib64/libgstplay-1.0.so
/V3/usr/lib64/libgstplayer-1.0.so
/V3/usr/lib64/libgstsctp-1.0.so
/V3/usr/lib64/libgsttranscoder-1.0.so
/V3/usr/lib64/libgsturidownloader-1.0.so
/V3/usr/lib64/libgstva-1.0.so
/V3/usr/lib64/libgstwayland-1.0.so
/V3/usr/lib64/libgstwebrtc-1.0.so
/V3/usr/lib64/libgstwebrtcnice-1.0.so
/V4/usr/lib64/libgstadaptivedemux-1.0.so
/V4/usr/lib64/libgstbadaudio-1.0.so
/V4/usr/lib64/libgstbasecamerabinsrc-1.0.so
/V4/usr/lib64/libgstcodecparsers-1.0.so
/V4/usr/lib64/libgstcodecs-1.0.so
/V4/usr/lib64/libgstcuda-1.0.so
/V4/usr/lib64/libgstinsertbin-1.0.so
/V4/usr/lib64/libgstisoff-1.0.so
/V4/usr/lib64/libgstmpegts-1.0.so
/V4/usr/lib64/libgstphotography-1.0.so
/V4/usr/lib64/libgstplay-1.0.so
/V4/usr/lib64/libgstplayer-1.0.so
/V4/usr/lib64/libgstsctp-1.0.so
/V4/usr/lib64/libgsttranscoder-1.0.so
/V4/usr/lib64/libgsturidownloader-1.0.so
/V4/usr/lib64/libgstva-1.0.so
/V4/usr/lib64/libgstwayland-1.0.so
/V4/usr/lib64/libgstwebrtc-1.0.so
/V4/usr/lib64/libgstwebrtcnice-1.0.so
/usr/include/gstreamer-1.0/gst/audio/audio-bad-prelude.h
/usr/include/gstreamer-1.0/gst/audio/gstnonstreamaudiodecoder.h
/usr/include/gstreamer-1.0/gst/audio/gstplanaraudioadapter.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/basecamerabinsrc-prelude.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstbasecamerasrc.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstcamerabin-enum.h
/usr/include/gstreamer-1.0/gst/basecamerabinsrc/gstcamerabinpreview.h
/usr/include/gstreamer-1.0/gst/codecparsers/codecparsers-prelude.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstav1parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gsth264parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gsth265parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstjpeg2000sampling.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstjpegparser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpeg4parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpegvideometa.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstmpegvideoparser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvc1parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp8parser.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp8rangedecoder.h
/usr/include/gstreamer-1.0/gst/codecparsers/gstvp9parser.h
/usr/include/gstreamer-1.0/gst/cuda/cuda-gst.h
/usr/include/gstreamer-1.0/gst/cuda/cuda-prelude.h
/usr/include/gstreamer-1.0/gst/cuda/gstcudabufferpool.h
/usr/include/gstreamer-1.0/gst/cuda/gstcudacontext.h
/usr/include/gstreamer-1.0/gst/cuda/gstcudaloader.h
/usr/include/gstreamer-1.0/gst/cuda/gstcudamemory.h
/usr/include/gstreamer-1.0/gst/cuda/gstcudanvrtc.h
/usr/include/gstreamer-1.0/gst/cuda/gstcudautils.h
/usr/include/gstreamer-1.0/gst/insertbin/gstinsertbin.h
/usr/include/gstreamer-1.0/gst/interfaces/photography-enumtypes.h
/usr/include/gstreamer-1.0/gst/interfaces/photography-prelude.h
/usr/include/gstreamer-1.0/gst/interfaces/photography.h
/usr/include/gstreamer-1.0/gst/isoff/gstisoff.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-atsc-descriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-atsc-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-dvb-descriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-dvb-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-hdmv-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-isdb-descriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gst-scte-section.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegts-enumtypes.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegtsdescriptor.h
/usr/include/gstreamer-1.0/gst/mpegts/gstmpegtssection.h
/usr/include/gstreamer-1.0/gst/mpegts/mpegts-prelude.h
/usr/include/gstreamer-1.0/gst/mpegts/mpegts.h
/usr/include/gstreamer-1.0/gst/play/gstplay-media-info.h
/usr/include/gstreamer-1.0/gst/play/gstplay-signal-adapter.h
/usr/include/gstreamer-1.0/gst/play/gstplay-types.h
/usr/include/gstreamer-1.0/gst/play/gstplay-video-overlay-video-renderer.h
/usr/include/gstreamer-1.0/gst/play/gstplay-video-renderer.h
/usr/include/gstreamer-1.0/gst/play/gstplay-visualization.h
/usr/include/gstreamer-1.0/gst/play/gstplay.h
/usr/include/gstreamer-1.0/gst/play/play-prelude.h
/usr/include/gstreamer-1.0/gst/play/play.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-g-main-context-signal-dispatcher.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-media-info.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-signal-dispatcher.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-types.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-video-overlay-video-renderer.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-video-renderer.h
/usr/include/gstreamer-1.0/gst/player/gstplayer-visualization.h
/usr/include/gstreamer-1.0/gst/player/gstplayer.h
/usr/include/gstreamer-1.0/gst/player/player-prelude.h
/usr/include/gstreamer-1.0/gst/player/player.h
/usr/include/gstreamer-1.0/gst/sctp/sctp-prelude.h
/usr/include/gstreamer-1.0/gst/sctp/sctpreceivemeta.h
/usr/include/gstreamer-1.0/gst/sctp/sctpsendmeta.h
/usr/include/gstreamer-1.0/gst/transcoder/gsttranscoder-signal-adapter.h
/usr/include/gstreamer-1.0/gst/transcoder/gsttranscoder.h
/usr/include/gstreamer-1.0/gst/transcoder/transcoder-enumtypes.h
/usr/include/gstreamer-1.0/gst/transcoder/transcoder-prelude.h
/usr/include/gstreamer-1.0/gst/uridownloader/gstfragment.h
/usr/include/gstreamer-1.0/gst/uridownloader/gsturidownloader.h
/usr/include/gstreamer-1.0/gst/uridownloader/gsturidownloader_debug.h
/usr/include/gstreamer-1.0/gst/uridownloader/uridownloader-prelude.h
/usr/include/gstreamer-1.0/gst/va/gstva.h
/usr/include/gstreamer-1.0/gst/va/gstvaallocator.h
/usr/include/gstreamer-1.0/gst/va/gstvadisplay.h
/usr/include/gstreamer-1.0/gst/va/gstvadisplay_drm.h
/usr/include/gstreamer-1.0/gst/va/gstvadisplay_wrapped.h
/usr/include/gstreamer-1.0/gst/va/gstvapool.h
/usr/include/gstreamer-1.0/gst/va/gstvautils.h
/usr/include/gstreamer-1.0/gst/va/va-enumtypes.h
/usr/include/gstreamer-1.0/gst/va/va-prelude.h
/usr/include/gstreamer-1.0/gst/va/va_fwd.h
/usr/include/gstreamer-1.0/gst/wayland/gstwl_fwd.h
/usr/include/gstreamer-1.0/gst/wayland/gstwlbuffer.h
/usr/include/gstreamer-1.0/gst/wayland/gstwlcontext.h
/usr/include/gstreamer-1.0/gst/wayland/gstwldisplay.h
/usr/include/gstreamer-1.0/gst/wayland/gstwllinuxdmabuf.h
/usr/include/gstreamer-1.0/gst/wayland/gstwlshmallocator.h
/usr/include/gstreamer-1.0/gst/wayland/gstwlvideobufferpool.h
/usr/include/gstreamer-1.0/gst/wayland/gstwlvideoformat.h
/usr/include/gstreamer-1.0/gst/wayland/gstwlwindow.h
/usr/include/gstreamer-1.0/gst/wayland/wayland-prelude.h
/usr/include/gstreamer-1.0/gst/wayland/wayland.h
/usr/include/gstreamer-1.0/gst/webrtc/datachannel.h
/usr/include/gstreamer-1.0/gst/webrtc/dtlstransport.h
/usr/include/gstreamer-1.0/gst/webrtc/ice.h
/usr/include/gstreamer-1.0/gst/webrtc/icestream.h
/usr/include/gstreamer-1.0/gst/webrtc/icetransport.h
/usr/include/gstreamer-1.0/gst/webrtc/nice/nice.h
/usr/include/gstreamer-1.0/gst/webrtc/nice/nice_fwd.h
/usr/include/gstreamer-1.0/gst/webrtc/nice/nicestream.h
/usr/include/gstreamer-1.0/gst/webrtc/nice/nicetransport.h
/usr/include/gstreamer-1.0/gst/webrtc/rtcsessiondescription.h
/usr/include/gstreamer-1.0/gst/webrtc/rtpreceiver.h
/usr/include/gstreamer-1.0/gst/webrtc/rtpsender.h
/usr/include/gstreamer-1.0/gst/webrtc/rtptransceiver.h
/usr/include/gstreamer-1.0/gst/webrtc/sctptransport.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc-enumtypes.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc.h
/usr/include/gstreamer-1.0/gst/webrtc/webrtc_fwd.h
/usr/lib64/libgstadaptivedemux-1.0.so
/usr/lib64/libgstbadaudio-1.0.so
/usr/lib64/libgstbasecamerabinsrc-1.0.so
/usr/lib64/libgstcodecparsers-1.0.so
/usr/lib64/libgstcodecs-1.0.so
/usr/lib64/libgstcuda-1.0.so
/usr/lib64/libgstinsertbin-1.0.so
/usr/lib64/libgstisoff-1.0.so
/usr/lib64/libgstmpegts-1.0.so
/usr/lib64/libgstphotography-1.0.so
/usr/lib64/libgstplay-1.0.so
/usr/lib64/libgstplayer-1.0.so
/usr/lib64/libgstsctp-1.0.so
/usr/lib64/libgsttranscoder-1.0.so
/usr/lib64/libgsturidownloader-1.0.so
/usr/lib64/libgstva-1.0.so
/usr/lib64/libgstwayland-1.0.so
/usr/lib64/libgstwebrtc-1.0.so
/usr/lib64/libgstwebrtcnice-1.0.so
/usr/lib64/pkgconfig/gstreamer-bad-audio-1.0.pc
/usr/lib64/pkgconfig/gstreamer-codecparsers-1.0.pc
/usr/lib64/pkgconfig/gstreamer-cuda-1.0.pc
/usr/lib64/pkgconfig/gstreamer-insertbin-1.0.pc
/usr/lib64/pkgconfig/gstreamer-mpegts-1.0.pc
/usr/lib64/pkgconfig/gstreamer-photography-1.0.pc
/usr/lib64/pkgconfig/gstreamer-play-1.0.pc
/usr/lib64/pkgconfig/gstreamer-player-1.0.pc
/usr/lib64/pkgconfig/gstreamer-plugins-bad-1.0.pc
/usr/lib64/pkgconfig/gstreamer-sctp-1.0.pc
/usr/lib64/pkgconfig/gstreamer-transcoder-1.0.pc
/usr/lib64/pkgconfig/gstreamer-va-1.0.pc
/usr/lib64/pkgconfig/gstreamer-wayland-1.0.pc
/usr/lib64/pkgconfig/gstreamer-webrtc-1.0.pc
/usr/lib64/pkgconfig/gstreamer-webrtc-nice-1.0.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/gstreamer-1.0/libgstaccurip.so
/V3/usr/lib64/gstreamer-1.0/libgstadpcmdec.so
/V3/usr/lib64/gstreamer-1.0/libgstadpcmenc.so
/V3/usr/lib64/gstreamer-1.0/libgstaes.so
/V3/usr/lib64/gstreamer-1.0/libgstaiff.so
/V3/usr/lib64/gstreamer-1.0/libgstasfmux.so
/V3/usr/lib64/gstreamer-1.0/libgstaudiobuffersplit.so
/V3/usr/lib64/gstreamer-1.0/libgstaudiofxbad.so
/V3/usr/lib64/gstreamer-1.0/libgstaudiolatency.so
/V3/usr/lib64/gstreamer-1.0/libgstaudiomixmatrix.so
/V3/usr/lib64/gstreamer-1.0/libgstaudiovisualizers.so
/V3/usr/lib64/gstreamer-1.0/libgstautoconvert.so
/V3/usr/lib64/gstreamer-1.0/libgstavtp.so
/V3/usr/lib64/gstreamer-1.0/libgstbayer.so
/V3/usr/lib64/gstreamer-1.0/libgstbluez.so
/V3/usr/lib64/gstreamer-1.0/libgstbz2.so
/V3/usr/lib64/gstreamer-1.0/libgstcamerabin.so
/V3/usr/lib64/gstreamer-1.0/libgstclosedcaption.so
/V3/usr/lib64/gstreamer-1.0/libgstcodecalpha.so
/V3/usr/lib64/gstreamer-1.0/libgstcodectimestamper.so
/V3/usr/lib64/gstreamer-1.0/libgstcoloreffects.so
/V3/usr/lib64/gstreamer-1.0/libgstcolormanagement.so
/V3/usr/lib64/gstreamer-1.0/libgstcurl.so
/V3/usr/lib64/gstreamer-1.0/libgstdash.so
/V3/usr/lib64/gstreamer-1.0/libgstdebugutilsbad.so
/V3/usr/lib64/gstreamer-1.0/libgstdecklink.so
/V3/usr/lib64/gstreamer-1.0/libgstdtls.so
/V3/usr/lib64/gstreamer-1.0/libgstdvb.so
/V3/usr/lib64/gstreamer-1.0/libgstdvbsubenc.so
/V3/usr/lib64/gstreamer-1.0/libgstdvbsuboverlay.so
/V3/usr/lib64/gstreamer-1.0/libgstdvdspu.so
/V3/usr/lib64/gstreamer-1.0/libgstfaceoverlay.so
/V3/usr/lib64/gstreamer-1.0/libgstfbdevsink.so
/V3/usr/lib64/gstreamer-1.0/libgstfestival.so
/V3/usr/lib64/gstreamer-1.0/libgstfieldanalysis.so
/V3/usr/lib64/gstreamer-1.0/libgstfreeverb.so
/V3/usr/lib64/gstreamer-1.0/libgstfrei0r.so
/V3/usr/lib64/gstreamer-1.0/libgstgaudieffects.so
/V3/usr/lib64/gstreamer-1.0/libgstgdp.so
/V3/usr/lib64/gstreamer-1.0/libgstgeometrictransform.so
/V3/usr/lib64/gstreamer-1.0/libgstgtkwayland.so
/V3/usr/lib64/gstreamer-1.0/libgsthls.so
/V3/usr/lib64/gstreamer-1.0/libgstid3tag.so
/V3/usr/lib64/gstreamer-1.0/libgstinter.so
/V3/usr/lib64/gstreamer-1.0/libgstinterlace.so
/V3/usr/lib64/gstreamer-1.0/libgstipcpipeline.so
/V3/usr/lib64/gstreamer-1.0/libgstivfparse.so
/V3/usr/lib64/gstreamer-1.0/libgstivtc.so
/V3/usr/lib64/gstreamer-1.0/libgstjp2kdecimator.so
/V3/usr/lib64/gstreamer-1.0/libgstjpegformat.so
/V3/usr/lib64/gstreamer-1.0/libgstkms.so
/V3/usr/lib64/gstreamer-1.0/libgstlegacyrawparse.so
/V3/usr/lib64/gstreamer-1.0/libgstmidi.so
/V3/usr/lib64/gstreamer-1.0/libgstmpegpsdemux.so
/V3/usr/lib64/gstreamer-1.0/libgstmpegpsmux.so
/V3/usr/lib64/gstreamer-1.0/libgstmpegtsdemux.so
/V3/usr/lib64/gstreamer-1.0/libgstmpegtsmux.so
/V3/usr/lib64/gstreamer-1.0/libgstmsdk.so
/V3/usr/lib64/gstreamer-1.0/libgstmxf.so
/V3/usr/lib64/gstreamer-1.0/libgstnetsim.so
/V3/usr/lib64/gstreamer-1.0/libgstnvcodec.so
/V3/usr/lib64/gstreamer-1.0/libgstopenal.so
/V3/usr/lib64/gstreamer-1.0/libgstopenexr.so
/V3/usr/lib64/gstreamer-1.0/libgstopusparse.so
/V3/usr/lib64/gstreamer-1.0/libgstpcapparse.so
/V3/usr/lib64/gstreamer-1.0/libgstpnm.so
/V3/usr/lib64/gstreamer-1.0/libgstproxy.so
/V3/usr/lib64/gstreamer-1.0/libgstqroverlay.so
/V3/usr/lib64/gstreamer-1.0/libgstqsv.so
/V3/usr/lib64/gstreamer-1.0/libgstremovesilence.so
/V3/usr/lib64/gstreamer-1.0/libgstrfbsrc.so
/V3/usr/lib64/gstreamer-1.0/libgstrist.so
/V3/usr/lib64/gstreamer-1.0/libgstrsvg.so
/V3/usr/lib64/gstreamer-1.0/libgstrtmp2.so
/V3/usr/lib64/gstreamer-1.0/libgstrtpmanagerbad.so
/V3/usr/lib64/gstreamer-1.0/libgstrtponvif.so
/V3/usr/lib64/gstreamer-1.0/libgstsbc.so
/V3/usr/lib64/gstreamer-1.0/libgstsctp.so
/V3/usr/lib64/gstreamer-1.0/libgstsdpelem.so
/V3/usr/lib64/gstreamer-1.0/libgstsegmentclip.so
/V3/usr/lib64/gstreamer-1.0/libgstshm.so
/V3/usr/lib64/gstreamer-1.0/libgstsiren.so
/V3/usr/lib64/gstreamer-1.0/libgstsmooth.so
/V3/usr/lib64/gstreamer-1.0/libgstsmoothstreaming.so
/V3/usr/lib64/gstreamer-1.0/libgstsndfile.so
/V3/usr/lib64/gstreamer-1.0/libgstspeed.so
/V3/usr/lib64/gstreamer-1.0/libgstsrtp.so
/V3/usr/lib64/gstreamer-1.0/libgstsubenc.so
/V3/usr/lib64/gstreamer-1.0/libgstswitchbin.so
/V3/usr/lib64/gstreamer-1.0/libgsttimecode.so
/V3/usr/lib64/gstreamer-1.0/libgsttranscode.so
/V3/usr/lib64/gstreamer-1.0/libgstttmlsubs.so
/V3/usr/lib64/gstreamer-1.0/libgstuvch264.so
/V3/usr/lib64/gstreamer-1.0/libgstv4l2codecs.so
/V3/usr/lib64/gstreamer-1.0/libgstva.so
/V3/usr/lib64/gstreamer-1.0/libgstvideofiltersbad.so
/V3/usr/lib64/gstreamer-1.0/libgstvideoframe_audiolevel.so
/V3/usr/lib64/gstreamer-1.0/libgstvideoparsersbad.so
/V3/usr/lib64/gstreamer-1.0/libgstvideosignal.so
/V3/usr/lib64/gstreamer-1.0/libgstvmnc.so
/V3/usr/lib64/gstreamer-1.0/libgstwaylandsink.so
/V3/usr/lib64/gstreamer-1.0/libgstwebp.so
/V3/usr/lib64/gstreamer-1.0/libgstwebrtc.so
/V3/usr/lib64/gstreamer-1.0/libgsty4mdec.so
/V3/usr/lib64/libgstadaptivedemux-1.0.so.0
/V3/usr/lib64/libgstadaptivedemux-1.0.so.0.2202.0
/V3/usr/lib64/libgstbadaudio-1.0.so.0
/V3/usr/lib64/libgstbadaudio-1.0.so.0.2202.0
/V3/usr/lib64/libgstbasecamerabinsrc-1.0.so.0
/V3/usr/lib64/libgstbasecamerabinsrc-1.0.so.0.2202.0
/V3/usr/lib64/libgstcodecparsers-1.0.so.0
/V3/usr/lib64/libgstcodecparsers-1.0.so.0.2202.0
/V3/usr/lib64/libgstcodecs-1.0.so.0
/V3/usr/lib64/libgstcodecs-1.0.so.0.2202.0
/V3/usr/lib64/libgstcuda-1.0.so.0
/V3/usr/lib64/libgstcuda-1.0.so.0.2202.0
/V3/usr/lib64/libgstinsertbin-1.0.so.0
/V3/usr/lib64/libgstinsertbin-1.0.so.0.2202.0
/V3/usr/lib64/libgstisoff-1.0.so.0
/V3/usr/lib64/libgstisoff-1.0.so.0.2202.0
/V3/usr/lib64/libgstmpegts-1.0.so.0
/V3/usr/lib64/libgstmpegts-1.0.so.0.2202.0
/V3/usr/lib64/libgstphotography-1.0.so.0
/V3/usr/lib64/libgstphotography-1.0.so.0.2202.0
/V3/usr/lib64/libgstplay-1.0.so.0
/V3/usr/lib64/libgstplay-1.0.so.0.2202.0
/V3/usr/lib64/libgstplayer-1.0.so.0
/V3/usr/lib64/libgstplayer-1.0.so.0.2202.0
/V3/usr/lib64/libgstsctp-1.0.so.0
/V3/usr/lib64/libgstsctp-1.0.so.0.2202.0
/V3/usr/lib64/libgsttranscoder-1.0.so.0
/V3/usr/lib64/libgsturidownloader-1.0.so.0
/V3/usr/lib64/libgsturidownloader-1.0.so.0.2202.0
/V3/usr/lib64/libgstva-1.0.so.0
/V3/usr/lib64/libgstva-1.0.so.0.2202.0
/V3/usr/lib64/libgstwayland-1.0.so.0
/V3/usr/lib64/libgstwayland-1.0.so.0.2202.0
/V3/usr/lib64/libgstwebrtc-1.0.so.0
/V3/usr/lib64/libgstwebrtc-1.0.so.0.2202.0
/V3/usr/lib64/libgstwebrtcnice-1.0.so.0
/V3/usr/lib64/libgstwebrtcnice-1.0.so.0.2202.0
/V4/usr/lib64/gstreamer-1.0/libgstaccurip.so
/V4/usr/lib64/gstreamer-1.0/libgstadpcmdec.so
/V4/usr/lib64/gstreamer-1.0/libgstadpcmenc.so
/V4/usr/lib64/gstreamer-1.0/libgstaes.so
/V4/usr/lib64/gstreamer-1.0/libgstaiff.so
/V4/usr/lib64/gstreamer-1.0/libgstasfmux.so
/V4/usr/lib64/gstreamer-1.0/libgstaudiobuffersplit.so
/V4/usr/lib64/gstreamer-1.0/libgstaudiofxbad.so
/V4/usr/lib64/gstreamer-1.0/libgstaudiolatency.so
/V4/usr/lib64/gstreamer-1.0/libgstaudiomixmatrix.so
/V4/usr/lib64/gstreamer-1.0/libgstaudiovisualizers.so
/V4/usr/lib64/gstreamer-1.0/libgstautoconvert.so
/V4/usr/lib64/gstreamer-1.0/libgstavtp.so
/V4/usr/lib64/gstreamer-1.0/libgstbayer.so
/V4/usr/lib64/gstreamer-1.0/libgstbluez.so
/V4/usr/lib64/gstreamer-1.0/libgstbz2.so
/V4/usr/lib64/gstreamer-1.0/libgstcamerabin.so
/V4/usr/lib64/gstreamer-1.0/libgstclosedcaption.so
/V4/usr/lib64/gstreamer-1.0/libgstcodecalpha.so
/V4/usr/lib64/gstreamer-1.0/libgstcodectimestamper.so
/V4/usr/lib64/gstreamer-1.0/libgstcoloreffects.so
/V4/usr/lib64/gstreamer-1.0/libgstcolormanagement.so
/V4/usr/lib64/gstreamer-1.0/libgstcurl.so
/V4/usr/lib64/gstreamer-1.0/libgstdash.so
/V4/usr/lib64/gstreamer-1.0/libgstdebugutilsbad.so
/V4/usr/lib64/gstreamer-1.0/libgstdecklink.so
/V4/usr/lib64/gstreamer-1.0/libgstdtls.so
/V4/usr/lib64/gstreamer-1.0/libgstdvb.so
/V4/usr/lib64/gstreamer-1.0/libgstdvbsubenc.so
/V4/usr/lib64/gstreamer-1.0/libgstdvbsuboverlay.so
/V4/usr/lib64/gstreamer-1.0/libgstdvdspu.so
/V4/usr/lib64/gstreamer-1.0/libgstfaceoverlay.so
/V4/usr/lib64/gstreamer-1.0/libgstfbdevsink.so
/V4/usr/lib64/gstreamer-1.0/libgstfestival.so
/V4/usr/lib64/gstreamer-1.0/libgstfieldanalysis.so
/V4/usr/lib64/gstreamer-1.0/libgstfreeverb.so
/V4/usr/lib64/gstreamer-1.0/libgstfrei0r.so
/V4/usr/lib64/gstreamer-1.0/libgstgaudieffects.so
/V4/usr/lib64/gstreamer-1.0/libgstgdp.so
/V4/usr/lib64/gstreamer-1.0/libgstgeometrictransform.so
/V4/usr/lib64/gstreamer-1.0/libgstgtkwayland.so
/V4/usr/lib64/gstreamer-1.0/libgsthls.so
/V4/usr/lib64/gstreamer-1.0/libgstid3tag.so
/V4/usr/lib64/gstreamer-1.0/libgstinter.so
/V4/usr/lib64/gstreamer-1.0/libgstinterlace.so
/V4/usr/lib64/gstreamer-1.0/libgstipcpipeline.so
/V4/usr/lib64/gstreamer-1.0/libgstivfparse.so
/V4/usr/lib64/gstreamer-1.0/libgstivtc.so
/V4/usr/lib64/gstreamer-1.0/libgstjp2kdecimator.so
/V4/usr/lib64/gstreamer-1.0/libgstjpegformat.so
/V4/usr/lib64/gstreamer-1.0/libgstkms.so
/V4/usr/lib64/gstreamer-1.0/libgstlegacyrawparse.so
/V4/usr/lib64/gstreamer-1.0/libgstmidi.so
/V4/usr/lib64/gstreamer-1.0/libgstmpegpsdemux.so
/V4/usr/lib64/gstreamer-1.0/libgstmpegpsmux.so
/V4/usr/lib64/gstreamer-1.0/libgstmpegtsdemux.so
/V4/usr/lib64/gstreamer-1.0/libgstmpegtsmux.so
/V4/usr/lib64/gstreamer-1.0/libgstmsdk.so
/V4/usr/lib64/gstreamer-1.0/libgstmxf.so
/V4/usr/lib64/gstreamer-1.0/libgstnetsim.so
/V4/usr/lib64/gstreamer-1.0/libgstnvcodec.so
/V4/usr/lib64/gstreamer-1.0/libgstopenal.so
/V4/usr/lib64/gstreamer-1.0/libgstopenexr.so
/V4/usr/lib64/gstreamer-1.0/libgstopusparse.so
/V4/usr/lib64/gstreamer-1.0/libgstpcapparse.so
/V4/usr/lib64/gstreamer-1.0/libgstpnm.so
/V4/usr/lib64/gstreamer-1.0/libgstproxy.so
/V4/usr/lib64/gstreamer-1.0/libgstqroverlay.so
/V4/usr/lib64/gstreamer-1.0/libgstqsv.so
/V4/usr/lib64/gstreamer-1.0/libgstremovesilence.so
/V4/usr/lib64/gstreamer-1.0/libgstrfbsrc.so
/V4/usr/lib64/gstreamer-1.0/libgstrist.so
/V4/usr/lib64/gstreamer-1.0/libgstrsvg.so
/V4/usr/lib64/gstreamer-1.0/libgstrtmp2.so
/V4/usr/lib64/gstreamer-1.0/libgstrtpmanagerbad.so
/V4/usr/lib64/gstreamer-1.0/libgstrtponvif.so
/V4/usr/lib64/gstreamer-1.0/libgstsbc.so
/V4/usr/lib64/gstreamer-1.0/libgstsctp.so
/V4/usr/lib64/gstreamer-1.0/libgstsdpelem.so
/V4/usr/lib64/gstreamer-1.0/libgstsegmentclip.so
/V4/usr/lib64/gstreamer-1.0/libgstshm.so
/V4/usr/lib64/gstreamer-1.0/libgstsiren.so
/V4/usr/lib64/gstreamer-1.0/libgstsmooth.so
/V4/usr/lib64/gstreamer-1.0/libgstsmoothstreaming.so
/V4/usr/lib64/gstreamer-1.0/libgstsndfile.so
/V4/usr/lib64/gstreamer-1.0/libgstspeed.so
/V4/usr/lib64/gstreamer-1.0/libgstsrtp.so
/V4/usr/lib64/gstreamer-1.0/libgstsubenc.so
/V4/usr/lib64/gstreamer-1.0/libgstswitchbin.so
/V4/usr/lib64/gstreamer-1.0/libgsttimecode.so
/V4/usr/lib64/gstreamer-1.0/libgsttranscode.so
/V4/usr/lib64/gstreamer-1.0/libgstttmlsubs.so
/V4/usr/lib64/gstreamer-1.0/libgstuvch264.so
/V4/usr/lib64/gstreamer-1.0/libgstv4l2codecs.so
/V4/usr/lib64/gstreamer-1.0/libgstva.so
/V4/usr/lib64/gstreamer-1.0/libgstvideofiltersbad.so
/V4/usr/lib64/gstreamer-1.0/libgstvideoframe_audiolevel.so
/V4/usr/lib64/gstreamer-1.0/libgstvideoparsersbad.so
/V4/usr/lib64/gstreamer-1.0/libgstvideosignal.so
/V4/usr/lib64/gstreamer-1.0/libgstvmnc.so
/V4/usr/lib64/gstreamer-1.0/libgstwaylandsink.so
/V4/usr/lib64/gstreamer-1.0/libgstwebp.so
/V4/usr/lib64/gstreamer-1.0/libgstwebrtc.so
/V4/usr/lib64/gstreamer-1.0/libgsty4mdec.so
/V4/usr/lib64/libgstadaptivedemux-1.0.so.0
/V4/usr/lib64/libgstadaptivedemux-1.0.so.0.2202.0
/V4/usr/lib64/libgstbadaudio-1.0.so.0
/V4/usr/lib64/libgstbadaudio-1.0.so.0.2202.0
/V4/usr/lib64/libgstbasecamerabinsrc-1.0.so.0
/V4/usr/lib64/libgstbasecamerabinsrc-1.0.so.0.2202.0
/V4/usr/lib64/libgstcodecparsers-1.0.so.0
/V4/usr/lib64/libgstcodecparsers-1.0.so.0.2202.0
/V4/usr/lib64/libgstcodecs-1.0.so.0
/V4/usr/lib64/libgstcodecs-1.0.so.0.2202.0
/V4/usr/lib64/libgstcuda-1.0.so.0
/V4/usr/lib64/libgstcuda-1.0.so.0.2202.0
/V4/usr/lib64/libgstinsertbin-1.0.so.0
/V4/usr/lib64/libgstinsertbin-1.0.so.0.2202.0
/V4/usr/lib64/libgstisoff-1.0.so.0
/V4/usr/lib64/libgstisoff-1.0.so.0.2202.0
/V4/usr/lib64/libgstmpegts-1.0.so.0
/V4/usr/lib64/libgstmpegts-1.0.so.0.2202.0
/V4/usr/lib64/libgstphotography-1.0.so.0
/V4/usr/lib64/libgstphotography-1.0.so.0.2202.0
/V4/usr/lib64/libgstplay-1.0.so.0
/V4/usr/lib64/libgstplay-1.0.so.0.2202.0
/V4/usr/lib64/libgstplayer-1.0.so.0
/V4/usr/lib64/libgstplayer-1.0.so.0.2202.0
/V4/usr/lib64/libgstsctp-1.0.so.0
/V4/usr/lib64/libgstsctp-1.0.so.0.2202.0
/V4/usr/lib64/libgsttranscoder-1.0.so.0
/V4/usr/lib64/libgsturidownloader-1.0.so.0
/V4/usr/lib64/libgsturidownloader-1.0.so.0.2202.0
/V4/usr/lib64/libgstva-1.0.so.0
/V4/usr/lib64/libgstva-1.0.so.0.2202.0
/V4/usr/lib64/libgstwayland-1.0.so.0
/V4/usr/lib64/libgstwayland-1.0.so.0.2202.0
/V4/usr/lib64/libgstwebrtc-1.0.so.0
/V4/usr/lib64/libgstwebrtc-1.0.so.0.2202.0
/V4/usr/lib64/libgstwebrtcnice-1.0.so.0
/V4/usr/lib64/libgstwebrtcnice-1.0.so.0.2202.0
/usr/lib64/gstreamer-1.0/libgstaccurip.so
/usr/lib64/gstreamer-1.0/libgstadpcmdec.so
/usr/lib64/gstreamer-1.0/libgstadpcmenc.so
/usr/lib64/gstreamer-1.0/libgstaes.so
/usr/lib64/gstreamer-1.0/libgstaiff.so
/usr/lib64/gstreamer-1.0/libgstasfmux.so
/usr/lib64/gstreamer-1.0/libgstaudiobuffersplit.so
/usr/lib64/gstreamer-1.0/libgstaudiofxbad.so
/usr/lib64/gstreamer-1.0/libgstaudiolatency.so
/usr/lib64/gstreamer-1.0/libgstaudiomixmatrix.so
/usr/lib64/gstreamer-1.0/libgstaudiovisualizers.so
/usr/lib64/gstreamer-1.0/libgstautoconvert.so
/usr/lib64/gstreamer-1.0/libgstavtp.so
/usr/lib64/gstreamer-1.0/libgstbayer.so
/usr/lib64/gstreamer-1.0/libgstbluez.so
/usr/lib64/gstreamer-1.0/libgstbz2.so
/usr/lib64/gstreamer-1.0/libgstcamerabin.so
/usr/lib64/gstreamer-1.0/libgstclosedcaption.so
/usr/lib64/gstreamer-1.0/libgstcodecalpha.so
/usr/lib64/gstreamer-1.0/libgstcodectimestamper.so
/usr/lib64/gstreamer-1.0/libgstcoloreffects.so
/usr/lib64/gstreamer-1.0/libgstcolormanagement.so
/usr/lib64/gstreamer-1.0/libgstcurl.so
/usr/lib64/gstreamer-1.0/libgstdash.so
/usr/lib64/gstreamer-1.0/libgstdebugutilsbad.so
/usr/lib64/gstreamer-1.0/libgstdecklink.so
/usr/lib64/gstreamer-1.0/libgstdtls.so
/usr/lib64/gstreamer-1.0/libgstdvb.so
/usr/lib64/gstreamer-1.0/libgstdvbsubenc.so
/usr/lib64/gstreamer-1.0/libgstdvbsuboverlay.so
/usr/lib64/gstreamer-1.0/libgstdvdspu.so
/usr/lib64/gstreamer-1.0/libgstfaceoverlay.so
/usr/lib64/gstreamer-1.0/libgstfbdevsink.so
/usr/lib64/gstreamer-1.0/libgstfestival.so
/usr/lib64/gstreamer-1.0/libgstfieldanalysis.so
/usr/lib64/gstreamer-1.0/libgstfreeverb.so
/usr/lib64/gstreamer-1.0/libgstfrei0r.so
/usr/lib64/gstreamer-1.0/libgstgaudieffects.so
/usr/lib64/gstreamer-1.0/libgstgdp.so
/usr/lib64/gstreamer-1.0/libgstgeometrictransform.so
/usr/lib64/gstreamer-1.0/libgstgtkwayland.so
/usr/lib64/gstreamer-1.0/libgsthls.so
/usr/lib64/gstreamer-1.0/libgstid3tag.so
/usr/lib64/gstreamer-1.0/libgstinter.so
/usr/lib64/gstreamer-1.0/libgstinterlace.so
/usr/lib64/gstreamer-1.0/libgstipcpipeline.so
/usr/lib64/gstreamer-1.0/libgstivfparse.so
/usr/lib64/gstreamer-1.0/libgstivtc.so
/usr/lib64/gstreamer-1.0/libgstjp2kdecimator.so
/usr/lib64/gstreamer-1.0/libgstjpegformat.so
/usr/lib64/gstreamer-1.0/libgstkms.so
/usr/lib64/gstreamer-1.0/libgstlegacyrawparse.so
/usr/lib64/gstreamer-1.0/libgstmidi.so
/usr/lib64/gstreamer-1.0/libgstmpegpsdemux.so
/usr/lib64/gstreamer-1.0/libgstmpegpsmux.so
/usr/lib64/gstreamer-1.0/libgstmpegtsdemux.so
/usr/lib64/gstreamer-1.0/libgstmpegtsmux.so
/usr/lib64/gstreamer-1.0/libgstmsdk.so
/usr/lib64/gstreamer-1.0/libgstmxf.so
/usr/lib64/gstreamer-1.0/libgstnetsim.so
/usr/lib64/gstreamer-1.0/libgstnvcodec.so
/usr/lib64/gstreamer-1.0/libgstopenal.so
/usr/lib64/gstreamer-1.0/libgstopenexr.so
/usr/lib64/gstreamer-1.0/libgstopusparse.so
/usr/lib64/gstreamer-1.0/libgstpcapparse.so
/usr/lib64/gstreamer-1.0/libgstpnm.so
/usr/lib64/gstreamer-1.0/libgstproxy.so
/usr/lib64/gstreamer-1.0/libgstqroverlay.so
/usr/lib64/gstreamer-1.0/libgstqsv.so
/usr/lib64/gstreamer-1.0/libgstremovesilence.so
/usr/lib64/gstreamer-1.0/libgstrfbsrc.so
/usr/lib64/gstreamer-1.0/libgstrist.so
/usr/lib64/gstreamer-1.0/libgstrsvg.so
/usr/lib64/gstreamer-1.0/libgstrtmp2.so
/usr/lib64/gstreamer-1.0/libgstrtpmanagerbad.so
/usr/lib64/gstreamer-1.0/libgstrtponvif.so
/usr/lib64/gstreamer-1.0/libgstsbc.so
/usr/lib64/gstreamer-1.0/libgstsctp.so
/usr/lib64/gstreamer-1.0/libgstsdpelem.so
/usr/lib64/gstreamer-1.0/libgstsegmentclip.so
/usr/lib64/gstreamer-1.0/libgstshm.so
/usr/lib64/gstreamer-1.0/libgstsiren.so
/usr/lib64/gstreamer-1.0/libgstsmooth.so
/usr/lib64/gstreamer-1.0/libgstsmoothstreaming.so
/usr/lib64/gstreamer-1.0/libgstsndfile.so
/usr/lib64/gstreamer-1.0/libgstspeed.so
/usr/lib64/gstreamer-1.0/libgstsrtp.so
/usr/lib64/gstreamer-1.0/libgstsubenc.so
/usr/lib64/gstreamer-1.0/libgstswitchbin.so
/usr/lib64/gstreamer-1.0/libgsttimecode.so
/usr/lib64/gstreamer-1.0/libgsttranscode.so
/usr/lib64/gstreamer-1.0/libgstttmlsubs.so
/usr/lib64/gstreamer-1.0/libgstuvch264.so
/usr/lib64/gstreamer-1.0/libgstv4l2codecs.so
/usr/lib64/gstreamer-1.0/libgstva.so
/usr/lib64/gstreamer-1.0/libgstvideofiltersbad.so
/usr/lib64/gstreamer-1.0/libgstvideoframe_audiolevel.so
/usr/lib64/gstreamer-1.0/libgstvideoparsersbad.so
/usr/lib64/gstreamer-1.0/libgstvideosignal.so
/usr/lib64/gstreamer-1.0/libgstvmnc.so
/usr/lib64/gstreamer-1.0/libgstwaylandsink.so
/usr/lib64/gstreamer-1.0/libgstwebp.so
/usr/lib64/gstreamer-1.0/libgstwebrtc.so
/usr/lib64/gstreamer-1.0/libgsty4mdec.so
/usr/lib64/libgstadaptivedemux-1.0.so.0
/usr/lib64/libgstadaptivedemux-1.0.so.0.2202.0
/usr/lib64/libgstbadaudio-1.0.so.0
/usr/lib64/libgstbadaudio-1.0.so.0.2202.0
/usr/lib64/libgstbasecamerabinsrc-1.0.so.0
/usr/lib64/libgstbasecamerabinsrc-1.0.so.0.2202.0
/usr/lib64/libgstcodecparsers-1.0.so.0
/usr/lib64/libgstcodecparsers-1.0.so.0.2202.0
/usr/lib64/libgstcodecs-1.0.so.0
/usr/lib64/libgstcodecs-1.0.so.0.2202.0
/usr/lib64/libgstcuda-1.0.so.0
/usr/lib64/libgstcuda-1.0.so.0.2202.0
/usr/lib64/libgstinsertbin-1.0.so.0
/usr/lib64/libgstinsertbin-1.0.so.0.2202.0
/usr/lib64/libgstisoff-1.0.so.0
/usr/lib64/libgstisoff-1.0.so.0.2202.0
/usr/lib64/libgstmpegts-1.0.so.0
/usr/lib64/libgstmpegts-1.0.so.0.2202.0
/usr/lib64/libgstphotography-1.0.so.0
/usr/lib64/libgstphotography-1.0.so.0.2202.0
/usr/lib64/libgstplay-1.0.so.0
/usr/lib64/libgstplay-1.0.so.0.2202.0
/usr/lib64/libgstplayer-1.0.so.0
/usr/lib64/libgstplayer-1.0.so.0.2202.0
/usr/lib64/libgstsctp-1.0.so.0
/usr/lib64/libgstsctp-1.0.so.0.2202.0
/usr/lib64/libgsttranscoder-1.0.so.0
/usr/lib64/libgsturidownloader-1.0.so.0
/usr/lib64/libgsturidownloader-1.0.so.0.2202.0
/usr/lib64/libgstva-1.0.so.0
/usr/lib64/libgstva-1.0.so.0.2202.0
/usr/lib64/libgstwayland-1.0.so.0
/usr/lib64/libgstwayland-1.0.so.0.2202.0
/usr/lib64/libgstwebrtc-1.0.so.0
/usr/lib64/libgstwebrtc-1.0.so.0.2202.0
/usr/lib64/libgstwebrtcnice-1.0.so.0
/usr/lib64/libgstwebrtcnice-1.0.so.0.2202.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gst-plugins-bad/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/gst-plugins-bad/065e53e772f604ccf39b435c4bc791d942279064
/usr/share/package-licenses/gst-plugins-bad/22990b105a08bb838c95fcc4bc5450c6dfdc79ac
/usr/share/package-licenses/gst-plugins-bad/4dbe7c1f3a1833a88333a7c282119323e9ef44fa
/usr/share/package-licenses/gst-plugins-bad/5b574b9029338b80cc6df610d503db509d783ec8
/usr/share/package-licenses/gst-plugins-bad/da14fe4b0940c1e74ce043eddb8fc00f28516b62

%files locales -f gst-plugins-bad-1.0.lang
%defattr(-,root,root,-)

